# Generated by Django 3.2.25 on 2024-08-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('possg', '0004_jobrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='subject',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
